---
###############################################################################
# Manager MariaDB Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   db_maria_user: string maria username.
#   db_maria_group: string maria group.
#   db_db_maria_create_user: boolean true to create role default user.
#   db_maria_default_user: dict containing builitin.user options for maria.
#   db_maria_default_group: dict containing builitin.group options for maria.

- name: 'manage users | confirm user exists'
  ansible.builtin.command: 'id {{ db_maria_user }}'
  register: _maria_user_exists
  changed_when: _maria_user_exists.rc > 0
  failed_when: false

- name: 'manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ db_maria_group }}'
  register: _maria_group_exists
  changed_when: _maria_group_exists.rc > 0
  failed_when: false

- name: 'manage users | create maria group'
  ansible.builtin.group:
    name:  '{{ db_maria_default_group.name }}'
    gid:   '{{ db_maria_default_group.gid }}'
    state: 'present'
  when: db_maria_create_user and _maria_group_exists.rc != 0

- name: 'manage users | create maria user (logins disabled)'
  ansible.builtin.user:
    name:            '{{ db_maria_default_user.name }}'
    group:           '{{ db_maria_default_user.group }}'
    uid:             '{{ db_maria_default_user.uid }}'
    shell:           '{{ db_maria_default_user.shell }}'
    home:            '{{ db_maria_default_user.home }}'
    comment:         '{{ db_maria_default_user.comment }}'
    create_home:     '{{ db_maria_default_user.create_home }}'
    password:        '{{ db_maria_default_user.password }}'
    password_lock:   '{{ db_maria_default_user.password_lock }}'
    update_password: '{{ db_maria_default_user.update_password }}'
    expires:         '{{ db_maria_default_user.expires }}'
    system:          '{{ db_maria_default_user.system }}'
    state:           'present'
  when: db_maria_create_user and _maria_user_exists.rc != 0
