---
###############################################################################
# Postgres Handlers
###############################################################################

- name: 'restart postgres'
  ansible.builtin.service:
    name:  'postgresql'
    state: 'restarted'
